export const DEFAULT_CATALOG_ITEMS = [
  {
    _id: 'demo-prod-1',
    title: 'QuantumBook Pro M3 16-inch Workstation',
    description: 'Ultimate power for engineers, creators, and AI researchers with neural engine accelerators, Liquid Retina XDR 120Hz display, and 24-hour battery endurance.',
    category: 'Electronics',
    tags: ['laptop', 'workstation', 'm3', 'apple', 'developer', 'electronics', 'pro'],
    price: 2499.0,
    discountPrice: 2299.0,
    stock: 35,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      { sku: 'QBK-16-512GB-SPACE', attributes: { color: 'Space Gray', storage: '512GB' }, price: 2299.0, stock: 15 },
      { sku: 'QBK-16-1TB-SPACE', attributes: { color: 'Space Gray', storage: '1TB' }, price: 2599.0, stock: 12 },
    ],
    features: ['16.2-inch Liquid Retina XDR Display', '36GB Unified Memory', 'Hardware-accelerated ray tracing', 'MagSafe fast charging'],
    originCity: 'San Francisco, CA',
    deliveryZones: ['Nationwide', 'West Coast'],
    estimatedDeliveryDays: 2,
    shippingRate: 0,
    storeId: { _id: 'demo-store-1', storeName: 'TechSphere Official' },
    ratingAverage: 4.9,
    ratingCount: 18,
    isApproved: true,
  },
  {
    _id: 'demo-prod-2',
    title: 'Aura ANC Wireless Noise-Cancelling Headphones',
    description: 'Immersive spatial audio with custom 40mm titanium dynamic drivers, hybrid active noise cancellation, and plush memory foam headband for all-day focus.',
    category: 'Audio',
    tags: ['headphones', 'anc', 'wireless', 'bluetooth', 'audio', 'noise-cancelling', 'music'],
    price: 349.0,
    discountPrice: 299.0,
    stock: 60,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      { sku: 'AURA-BLK', attributes: { color: 'Matte Black' }, price: 299.0, stock: 30 },
      { sku: 'AURA-WHT', attributes: { color: 'Ivory White' }, price: 299.0, stock: 30 },
    ],
    features: ['45-hour playback on single charge', 'Hybrid Active Noise Cancellation with Transparency Mode', 'Hi-Res Audio LDAC certification'],
    originCity: 'New York, NY',
    deliveryZones: ['Nationwide', 'East Coast'],
    estimatedDeliveryDays: 3,
    shippingRate: 0,
    storeId: { _id: 'demo-store-1', storeName: 'TechSphere Official' },
    ratingAverage: 4.8,
    ratingCount: 42,
    isApproved: true,
  },
  {
    _id: 'demo-prod-3',
    title: 'ApexErgo Mechanical Wireless Keyboard (Hot-Swap)',
    description: 'Precision typing instrument with aircraft-grade aluminum chassis, south-facing RGB per-key illumination, and lubed mechanical switches for buttery acoustics.',
    category: 'Electronics',
    tags: ['keyboard', 'mechanical', 'rgb', 'gadget', 'wireless', 'accessories'],
    price: 189.0,
    discountPrice: 159.0,
    stock: 45,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      { sku: 'APX-RED', attributes: { switch: 'Linear Red', color: 'Stealth Black' }, price: 159.0, stock: 25 },
      { sku: 'APX-BRN', attributes: { switch: 'Tactile Brown', color: 'Retro White' }, price: 159.0, stock: 20 },
    ],
    features: ['Hot-swappable PCB (3/5-pin compatible)', 'Gasket mounted sound dampening', 'Tri-mode connection (Bluetooth 5.2 / 2.4GHz / USB-C)'],
    originCity: 'Austin, TX',
    deliveryZones: ['Nationwide', 'Central'],
    estimatedDeliveryDays: 3,
    shippingRate: 0,
    storeId: { _id: 'demo-store-1', storeName: 'TechSphere Official' },
    ratingAverage: 4.7,
    ratingCount: 29,
    isApproved: true,
  },
  {
    _id: 'demo-prod-4',
    title: 'Organic Heavyweight French Terry Hoodie',
    description: 'Crafted from 100% GOTS-certified organic cotton with double-needle construction, pre-shrunk finish, and a relaxed contemporary drape.',
    category: 'Apparel',
    tags: ['hoodie', 'organic', 'cotton', 'clothing', 'fashion', 'streetwear', 'comfort'],
    price: 110.0,
    discountPrice: 88.0,
    stock: 50,
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      { sku: 'HD-BLK-M', attributes: { size: 'M', color: 'Washed Black' }, price: 88.0, stock: 20 },
      { sku: 'HD-BLK-L', attributes: { size: 'L', color: 'Washed Black' }, price: 88.0, stock: 15 },
    ],
    features: ['450 GSM French Terry Cotton', 'Garment dyed with low-impact certified pigments', 'Ribbed cuffs and waistband'],
    originCity: 'Portland, OR',
    deliveryZones: ['Nationwide', 'West Coast'],
    estimatedDeliveryDays: 4,
    shippingRate: 5.99,
    storeId: { _id: 'demo-store-2', storeName: 'EcoVibe Studio' },
    ratingAverage: 4.9,
    ratingCount: 35,
    isApproved: true,
  },
];
